


extends Resource
var shader_code: = \
\
\
\
\
\
\
\
\
\
\
\
\
\
\
\
\
\
\
\
\
\
\
\
\
\
\
\
\
\
\
\
\
\
\
\
\
\
\
\
\
\
\
\
\
\
\
\
\
\
\
\
\
\
\
\
\
\
\
\
\
\
\
\
\
\
\
\
\
\
\
\
\
\
\
\
\
\
\
\
\
\
\
\
\
\
\
\
\
\
\
\
\
\
\
\
\
\
\
\
\
\
\
\
"\r\nshader_type canvas_item;\r\nuniform vec4 sm_highlight_entity : hint_color;\r\nuniform bool sm_is_render_entity_highlight = false;\r\nuniform bool is_render_mode_simulation \t\t= false;\r\nuniform bool sm_is_render_with_paint\t\t= true;\r\nuniform bool ed_is_layer_paint_type_on \t\t= true;\r\nuniform float ed_paint_overlay_intensity \t= 0.0;\r\nuniform sampler2D smp_ed_logic;\r\nuniform sampler2D smp_ed_paint_on;\r\nuniform sampler2D smp_ed_paint_off;\r\nuniform sampler2D smp_sm_state;\r\nuniform sampler2D smp_sm_die;\r\nuniform sampler2D smp_sm_buslut;\r\nuniform sampler2D smp_sm_busentities;\r\nuniform float busentities_sidelength = 0.0;\r\nuniform sampler2D smp_sm_on;\r\nuniform sampler2D smp_sm_off;\r\nuniform sampler2D smp_sm_led_palette;\r\nconst float MAX_BUS_ITERATIONS = 32.0;\r\nconst float LED_RAWTYPE = 12.0;\r\nconst float EPSILON = 0.001;\r\nbool bapprox_eq_vec4(vec4 a, vec4 b) {\r\n\treturn all(lessThan(abs(a - b), vec4(EPSILON)));\r\n}\r\nbool bapprox_eq(float a, float b) {\r\n\treturn (abs(a - b) < EPSILON);\r\n}\r\nfloat fapprox_eq(float a, float b) {\r\n\treturn float(abs(a - b) < EPSILON);\r\n}\r\nvec4 get_texel(sampler2D p_smp, vec2 p_coord) {\r\n\tvec2 texel_size = 1.0 / vec2(textureSize(p_smp, 0));\r\n\tvec2 texel_pos = (p_coord * texel_size) + (texel_size * 0.5);\r\n\treturn texture(p_smp, texel_pos);\r\n}\r\nvoid fragment(){\r\n\tvec4 tex_ed_logic = texture(smp_ed_logic, UV);\r\n\tvec4 tex_ed_paint_on = texture(smp_ed_paint_on, UV);\r\n\tvec4 tex_ed_paint_off = texture(smp_ed_paint_off, UV);\r\n\tvec4 tex_ed_paint = mix(tex_ed_paint_off, tex_ed_paint_on, float(ed_is_layer_paint_type_on));\r\n\tfloat ed_paint_overlay_mix = tex_ed_paint.a * tex_ed_logic.a * ed_paint_overlay_intensity;\r\n\tvec4 tex_editor = vec4(mix(tex_ed_logic.rgb, tex_ed_paint.rgb, ed_paint_overlay_mix), tex_ed_logic.a);\r\n\tvec4 die = texture(smp_sm_die, UV);\r\n\tvec4 tex_sm_on = texture(smp_sm_on, UV);\r\n\tvec4 tex_sm_off = texture(smp_sm_off, UV);\r\n\tvec4 tex_sm_led_palette = texture(smp_sm_led_palette, UV);\r\n\tvec4 buslut = texture(smp_sm_buslut, UV);\r\n\tvec2 coords = round((vec2(die.r, die.b) * 255.0) + (vec2(die.g, die.a) * 255.0 * 256.0));\r\n\tfloat is_bus = float(bapprox_eq(coords.x, 65535) && bapprox_eq(coords.y, 65535));\r\n\tvec4 entity_data = get_texel(smp_sm_state, coords * (1.0 - is_bus));\r\n\tvec3 DEBUG_bus_end = vec3(0, 0, 0);\r\n\tvec2 buscoords = round((vec2(buslut.r, buslut.b) * 255.0) + (vec2(buslut.g, buslut.a) * 255.0 * 256.0));\r\n\tfloat busindex = round(buscoords.y * busentities_sidelength + buscoords.x);\r\n\tbool is_bus_hhe = false;\r\n\tfloat is_bus_on = 0.0;\r\n\tint steps = int(round(MAX_BUS_ITERATIONS * is_bus));\r\n\tfor (int i = 0; i < steps; i++) {\r\n\t\tDEBUG_bus_end.b = 1.0;\r\n\t\tvec2 entitycoord = round(vec2(mod(busindex, busentities_sidelength), floor(busindex / busentities_sidelength)));\r\n\t\tvec4 entitylookup = get_texel(smp_sm_busentities, entitycoord);\r\n\t\tvec2 enlucoords = round((vec2(entitylookup.r, entitylookup.b) * 255.0) + (vec2(entitylookup.g, entitylookup.a) * 255.0 * 256.0));\r\n\t\tif (bapprox_eq(enlucoords.x, 0) && bapprox_eq(enlucoords.y, 0)) {\r\n\t\t\tDEBUG_bus_end.r = 1.0;\r\n\t\t\tDEBUG_bus_end.b = 0.0;\r\n\t\t\tbreak;\r\n\t\t}\r\n\t\tif (bapprox_eq_vec4(entitylookup, sm_highlight_entity)) {\r\n\t\t\tis_bus_hhe = true;\r\n\t\t\tDEBUG_bus_end = vec3(0.5);\r\n\t\t\tbreak;\r\n\t\t}\r\n\t\tvec4 enlu_data = get_texel(smp_sm_state, enlucoords);\r\n\t\tfloat is_on = ceil(enlu_data.r);\r\n\t\tif (bapprox_eq(is_on, 1.0)) {\r\n\t\t\tis_bus_on = 1.0;\r\n\t\t\tDEBUG_bus_end.g = 1.0;\r\n\t\t\tDEBUG_bus_end.b = 0.0;\r\n\t\t\tif (!sm_is_render_entity_highlight) {\r\n\t\t\t\tbreak;\r\n\t\t\t}\r\n\t\t}\r\n\t\tbusindex = round(busindex + 1.0);\r\n\t}\r\n\tfloat is_on = ceil(entity_data.r) + is_bus_on; \r\n\tvec4 tex_sm_normal = mix(tex_sm_off, tex_sm_on, is_on);\r\n\tvec4 tex_sm_paint = mix(tex_ed_paint_off, tex_ed_paint_on, is_on);\r\n\tfloat is_led = fapprox_eq(round(entity_data.g * 255.0), LED_RAWTYPE); \r\n\tfloat led_index = round(min(entity_data.a * 255.0, 15.0)); \r\n\tvec4 led_color = get_texel(smp_sm_led_palette, vec2(led_index, 0.0));\r\n\tvec4 tex_sm_paint_led = mix(tex_ed_paint_on, tex_ed_paint_off, fapprox_eq(led_index, 0.0));\r\n\ttex_sm_paint_led = mix(vec4(1.0), tex_sm_paint_led, tex_sm_paint_led.a);\r\n\ttex_sm_paint_led *= led_color;\r\n\tvec4 tex_simulation = mix(tex_sm_normal, tex_sm_paint, float(sm_is_render_with_paint) * tex_sm_paint.a);\r\n\ttex_simulation.a = tex_ed_logic.a;\r\n\ttex_simulation = mix(tex_simulation, tex_sm_paint_led, is_led * tex_ed_logic.a);\r\n\ttex_simulation = mix(\r\n\t\ttex_simulation,\r\n\t\tvec4(vec3((sin(TIME * 10.0) + 1.0) / 2.0), 1),\r\n\t\tfloat(bapprox_eq_vec4(die, sm_highlight_entity) || is_bus_hhe) * float(sm_is_render_entity_highlight)\r\n\t);\r\n\tCOLOR = mix(tex_editor, tex_simulation, float(is_render_mode_simulation));\r\n}\r\n\r\n"